  version: "3.8"

  services:
    app:
      build:
        context: .
        dockerfile: config/Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=${DATABASE_DOCKER_URL}
        - NEXT_WEBPACK_USEPOLLING=0
        - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
        - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
        - HOST=${HOST}
      volumes:
        - ./src:/usr/src/app
    db:
      image: postgres
      restart: always
      environment:
        PGUSER: ${POSTGRES_USER}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - db-data:/var/lib/postgresql/data

  volumes:
    db-data:
