  version: "3.8"

  services:
    app:
      build:
        context: .
        dockerfile: config/Dockerfile
      depends_on:
        - db
      ports:
        - "80:80"
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
        - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
        - HOST=${HOST}
        - PORT=${PORT}
        - NEXT_WEBPACK_USEPOLLING=0

    db:
      image: postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - PGUSER=${PGUSER}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}


  volumes:
    db-data:
