  version: "3.8"

  services:
    app:
      build:
        context: .
        dockerfile: config/Dockerfile
      depends_on:
        - db
      ports:
        - "80:80"
      environment:
        - NEXT_WEBPACK_USEPOLLING=0
      env_file:
        - ./.env.production

    db:
      image: postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
      env_file:
        - ./.env.production


  volumes:
    db-data:
