import './globals.css'
import {ContainerWide} from "@/app/Components/Atoms/";
import {AuthProvider} from "@/Utils/Contexts/AuthContext";
import Header from "@/app/Components/Organisms/Header/Header"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'body'}>
      <AuthProvider>
        <Header></Header>
            <ContainerWide>
              {children}
            </ContainerWide>
      </AuthProvider>
      </body>
    </html>
  )
}
