import './globals.css'
import {ContainerWide} from "@/app/Components/Atoms/";
import RegistrationForm from "@/app/Components/Organisms/Forms/RegistrationForm/RegistrationForm";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'body'}>
          <ContainerWide>
              {children}
          </ContainerWide>
      </body>
    </html>
  )
}
