FROM node:16-alpine

# Installation des dépendances pour PostgreSQL
RUN apk update && apk add postgresql postgresql-client

# Création de l'utilisateur PostgreSQL avec le nom d'utilisateur et le mot de passe personnalisés

# Création du répertoire de travail
WORKDIR /app

# Installation des dépendances de l'application
COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npm install -g prisma@4.16.2

RUN npx prisma generate

# Copie des fichiers de l'application
COPY . .

# Exposition du port 3000 utilisé par l'application
EXPOSE 3000

# Commande de démarrage de l'application
CMD ["./config/startup_dev.sh"]

